# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20210318_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='precipitation',
            new_name='Precipitation',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='temperature',
            new_name='Temperature',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='forecast_time',
            new_name='forecastTime',
        ),
    ]
