# Generated by Django 3.1.7 on 2021-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_auto_20210318_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecastsum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='lon')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('temp_max', models.FloatField(verbose_name='temperature max')),
                ('temp_min', models.FloatField(verbose_name='temperature min')),
                ('temp_avg', models.FloatField(verbose_name='temperature avg')),
                ('Prec_max', models.FloatField(verbose_name='precipitation max')),
                ('Prec_min', models.FloatField(verbose_name='precipitation min')),
                ('Prec_avg', models.FloatField(verbose_name='precipitation avg')),
            ],
        ),
    ]
